CREATE TABLE peliculas ( id BIGINT PRIMARY KEY AUTO_INCREMENT, titulo VARCHAR(200) UNIQUE NOT NULL, duracion_min INT NOT NULL, clasificacion VARCHAR(32) NOT NULL );
CREATE TABLE salas ( id VARCHAR(50) PRIMARY KEY, filas INT NOT NULL, butacas_por_fila INT NOT NULL );
CREATE TABLE sesiones ( id BIGINT PRIMARY KEY AUTO_INCREMENT, pelicula_id BIGINT NOT NULL, sala_id VARCHAR(50) NOT NULL, fecha_hora DATETIME NOT NULL, precio_base DOUBLE NOT NULL );
CREATE TABLE clientes ( id BIGINT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(120) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL );
CREATE TABLE cuentas ( id BIGINT PRIMARY KEY AUTO_INCREMENT, cliente_id BIGINT UNIQUE NOT NULL, saldo DOUBLE NOT NULL );
CREATE TABLE entradas ( id BIGINT PRIMARY KEY AUTO_INCREMENT, sesion_id BIGINT NOT NULL, fila INT NOT NULL, columna INT NOT NULL, cliente_id BIGINT NOT NULL, precio DOUBLE NOT NULL, UNIQUE (sesion_id,fila,columna) );
